import {useEffect,useMemo,useState} from 'react'
import {Plus,RefreshCw,Search,CheckSquare,Square} from 'lucide-react'
import PageHeader from '../components/PageHeader';import TaskRow from '../components/TaskRow';import CompletionDrawer from '../components/CompletionDrawer';import {fetchDelegation,fetchDelegationHistory,visibleToUser} from '../services/tasks'
export default function Delegation({session,setPage,refresh,onChanged}){
 const canEdit=session?.isAdmin||['Editor','Full Access'].includes(session?.access?.Delegation)
 const [current,setCurrent]=useState([]),[history,setHistory]=useState([]),[tab,setTab]=useState('current'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[selected,setSelected]=useState(new Set()),[drawer,setDrawer]=useState(null)
 const load=async()=>{setLoading(true);setError('');try{const [a,b]=await Promise.all([fetchDelegation(),fetchDelegationHistory()]);setCurrent(visibleToUser(a,session));setHistory(visibleToUser(b,session));setSelected(new Set())}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[refresh,session.username])
 const list=useMemo(()=> (tab==='current'?current:history).filter(t=>!q||`${t.title} ${t.assignee} ${t.givenBy} ${t.id}`.toLowerCase().includes(q.toLowerCase())),[tab,current,history,q])
 const pending=canEdit?list.filter(t=>String(t.liveStatus||t.status).toLowerCase()!=='done'):[], allSelected=pending.length>0&&pending.every(t=>selected.has(`${t.type}:${t.id}`))
 const toggle=t=>setSelected(prev=>{const n=new Set(prev),k=`${t.type}:${t.id}`;n.has(k)?n.delete(k):n.add(k);return n})
 const toggleAll=()=>setSelected(allSelected?new Set():new Set(pending.map(t=>`${t.type}:${t.id}`)))
 const selectedTasks=list.filter(t=>selected.has(`${t.type}:${t.id}`))
 return <><PageHeader title="Delegation" subtitle="Assign, monitor and submit delegated work." action={<div className="header-actions"><button className="secondary-btn" onClick={load}><RefreshCw size={15}/> Refresh</button><button style={{display:canEdit?'inline-flex':'none'}} className="primary-btn" onClick={()=>setPage('assign')}><Plus size={15}/> Assign Task</button>{selectedTasks.length>0&&tab==='current'&&<button className="primary-btn" onClick={()=>canEdit&&setDrawer(selectedTasks)}><CheckSquare size={15}/> Submit Selected ({selectedTasks.length})</button>}</div>}/><div className="mini-tabs"><button className={tab==='current'?'active':''} onClick={()=>{setTab('current');setSelected(new Set())}}>Current</button><button className={tab==='history'?'active':''} onClick={()=>{setTab('history');setSelected(new Set())}}>History</button></div><div className="toolbar"><div className="search-box"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search delegation..."/></div></div>{error&&<div className="error-box page-error">{error}</div>}<div className="panel"><div className="delegation-summary"><div><span>Visible tasks</span><b>{current.length}</b></div><div><span>Pending</span><b>{current.filter(x=>x.status.toLowerCase()!=='done').length}</b></div><div><span>History</span><b>{history.length}</b></div></div>{tab==='current'&&<div className="selection-bar"><button className="select-all-btn" onClick={toggleAll} disabled={!pending.length}>{allSelected?<CheckSquare size={17}/>:<Square size={17}/>}<b>{allSelected?'Clear All':'Select All'}</b><span>{selectedTasks.length} selected</span></button><small>{canEdit?`${pending.length} selectable`:'View only'}</small></div>}{loading?<div className="loading-box">Loading delegation…</div>:list.length?list.map(t=><TaskRow key={`${t.id}-${t.row}-${tab}`} task={t} selectable={tab==='current'&&canEdit} selected={selected.has(`${t.type}:${t.id}`)} onSelect={canEdit?toggle:undefined} onComplete={canEdit&&tab==='current'?task=>setDrawer([task]):undefined}/>):<div className="empty-box">No delegation records found.</div>}</div><CompletionDrawer tasks={drawer} onClose={()=>setDrawer(null)} onDone={()=>{setDrawer(null);load();onChanged?.()}}/></>
}
