import {useEffect,useMemo,useState} from 'react'
import PageHeader from '../components/PageHeader'
import {fetchChecklist,fetchDelegation,visibleToUser} from '../services/tasks'
export default function Reports({session,refresh}){
 const [tasks,setTasks]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{(async()=>{setLoading(true);try{const [c,d]=await Promise.all([fetchChecklist(),fetchDelegation()]);setTasks(visibleToUser([...c,...d],session))}catch(e){setError(e.message)}finally{setLoading(false)}})()},[refresh,session.username])
 const s=useMemo(()=>{const total=tasks.length,done=tasks.filter(t=>(t.liveStatus||t.status).toLowerCase()==='done').length,pending=tasks.filter(t=>(t.liveStatus||t.status).toLowerCase()!=='done').length,overdue=tasks.filter(t=>(t.liveStatus||t.status).toLowerCase()==='overdue').length,check=tasks.filter(t=>t.type==='Checklist'),del=tasks.filter(t=>t.type==='Delegation');const pct=a=>a.length?Math.round(a.filter(t=>(t.liveStatus||t.status).toLowerCase()==='done').length/a.length*1000)/10:0;return {total,done,pending,overdue,score:pct(tasks),checkScore:pct(check),delScore:pct(del),checkDone:check.filter(t=>(t.liveStatus||t.status).toLowerCase()==='done').length,delDone:del.filter(t=>(t.liveStatus||t.status).toLowerCase()==='done').length}},[tasks])
 return <><PageHeader title="Reports & Score" subtitle="Detailed live performance summary."/>{error&&<div className="error-box page-error">{error}</div>}{loading?<div className="panel loading-box">Calculating report…</div>:<>
  <div className="report-hero"><div className="panel"><small>Overall Live Score</small><strong>{s.score}%</strong><span>{s.done} completed of {s.total} visible tasks</span><div className="score-track large"><i style={{width:`${Math.min(s.score,100)}%`}}/></div></div><div className="panel"><div className="panel-head"><div><h2>Score Breakdown</h2><p>Short, detailed view of current performance.</p></div></div><div className="report-bars"><div><span>Checklist</span><i><em style={{width:`${s.checkScore}%`}}/></i><b>{s.checkScore}%</b></div><div><span>Delegation</span><i><em style={{width:`${s.delScore}%`}}/></i><b>{s.delScore}%</b></div></div></div></div>
  <div className="stats-grid"><div className="stat-card"><span>Completed</span><strong>{s.done}</strong><small>All visible tasks</small></div><div className="stat-card"><span>Pending</span><strong>{s.pending}</strong><small>Not yet completed</small></div><div className="stat-card"><span>Overdue</span><strong>{s.overdue}</strong><small>Needs attention</small></div><div className="stat-card"><span>Total</span><strong>{s.total}</strong><small>Current task base</small></div></div>
  <div className="content-grid"><div className="panel"><div className="panel-head"><div><h2>Detailed Structure</h2><p>Current counts used by the live percentage.</p></div></div><div className="score-lines"><div><span>Overall completed</span><b>{s.done}/{s.total}</b></div><div><span>Checklist completed</span><b>{s.checkDone}/{tasks.filter(t=>t.type==='Checklist').length}</b></div><div><span>Delegation completed</span><b>{s.delDone}/{tasks.filter(t=>t.type==='Delegation').length}</b></div><div><span>Pending</span><b>{s.pending}</b></div><div><span>Overdue</span><b>{s.overdue}</b></div></div></div><div className="panel"><div className="panel-head"><div><h2>Score Meaning</h2><p>Simple interpretation.</p></div></div><div className="summary-list"><div><span>90–100%</span><b>Excellent</b></div><div><span>75–89.9%</span><b>Good</b></div><div><span>50–74.9%</span><b>Needs focus</b></div><div><span>Below 50%</span><b>Attention required</b></div></div></div></div>
 </>}</>}
